apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocop-backend
  template:
    metadata:
      labels:
        app: ocop-backend
    spec:
      containers:
      - name: ocop-backend
        image: ocop-backend:1.0
        envFrom:
          - configMapRef:
              name: backend-config
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ocop-backend-service
spec:
  selector:
    app: ocop-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31998
  type: NodePort
